---
name: demo-workflow
on: push
jobs:
    firstJob:
        runs-on: ubuntu-latest
        steps:
            -   name: Prints welcome message
                run: echo "Welcome welcome welcome"
            -   name: List files
                run: ls
            -   name: Read file
                run: cat README.md
            