---
name: demo-workflow
on: push
jobs:
    firstJob:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Prints welcome message
                run: echo "Welcome welcome welcome"

            -   name: See the PWD
                run: pwd

            -   name: List all files
                run: ls -a

            -   name: Read file
                run: cat README.md
            